#测试环境
server:
  port: 14914
#  servlet:
#    encoding:
#      charset: GBK

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  banner:
    image:
      location: classpath:banner_fozu.txt

com:
  lanhuigu:
    canghaisangtian: cangHaiSangTian
    renjianzhengdao: renJianZhengDao

mycar:
  brand: BYD
  price: 120000
#debug: true

# yaml表示以上对象
person:
  userName: zhangsan
  boss: false
  birth: 2019/12/12 20:12:33
  age: 18
  pet:
    name: tomcat
    weight: 23.4
  #  interests: [篮球,游泳]
  interests:
    - 篮球
    - 游泳
  #  animal: [阿猫,阿狗]
  animal:
    - jerry
    - mario
  score:
    english:
      first: 30
      second: 40
      third: 50
    math: [131,140,148]
    chinese: {first: 128,second: 136}
  salarys: [3999,4999.98,5999.99]
  allPets:
    sick:
      - name: tom
        weight: 22
      - {name: jerry,weight: 47}
    health: [{name: mario,weight: 47}]
